### ISSUE TITLE
Use  conversation demo link

### ISSUE THREAD

**Issue by WentangChen** [TangYuan96/MiniGPT-3D#5]
我把链接http://127.0.0.1:7862放在浏览器之后，显示无法访问：
![image](https://github.com/user-attachments/assets/adaa8509-9444-4486-9e1b-be9a1717704d)
![image](https://github.com/user-attachments/assets/b23c3cfd-82a7-4453-b49e-b02f18e862e2)
请问这个怎么解决呀？

**Comment by TangYuan96** [comment]
Thanks for your interest in our work.

When using the link of the Gradio demo, there are two cases:

1. Running MiniGPT-3D on a **local server**, you can directly copy the link to the browser on the local server. Because both you and your local server are within the same local network (LAN), you can access the service.

2. Running MiniGPT-3D on a **remote server** and you wish to access the demo on your laptop's browser, you will first need to establish an SSH tunnel between your laptop and the remote server to project the service port of the remote server onto your laptop. Follow these instructions: 

    - **Way 1：**
    a.  open the cmd of windows (terminal of linux),
b. input `ssh -L 7860:127.0.0.1:7860 xiaoli@ip -p 22`, where ` xiaoli@ip -p 22` is your ssh login infor on remote server. 
c. copy link `127.0.0.1:7860` to  your laptop's browser

    - **Way 2** using mobaxterm：[CH Instr 1](https://www.cnblogs.com/KAWAKO/p/17077763.html),  [CH Instr 2](https://blog.csdn.net/xfysq_/article/details/138340373), [EN Instr 1](https://superuser.com/questions/1601631/create-ssh-tunnel-using-mobaxterm-on-windows),  [EN Instr 2](https://en-vegadocs.vega.izum.si/mobaxterm/)

**Comment by WentangChen** [comment]
> Thanks for your interest in our work.
> 
> When using the link of the Gradio demo, there are two cases:
> 
> 1. Running MiniGPT-3D on a **local server**, you can directly copy the link to the browser on the local server. Because both you and your local server are within the same local network (LAN), you can access the service.
> 2. Running MiniGPT-3D on a **remote server** and you wish to access the demo on your laptop's browser, you will first need to establish an SSH tunnel between your laptop and the remote server to project the service port of the remote server onto your laptop. Follow these instructions:
>    
>    * **Way 1：**
>      a.  open the cmd of windows (terminal of linux),
>      b. input `ssh -L 7860:127.0.0.1:7860 xiaoli@ip -p 22`, where ` xiaoli@ip -p 22` is your ssh login infor on remote server.
>      c. copy link `127.0.0.1:7860` to  your laptop's browser
>    * **Way 2** using mobaxterm：[CH Instr 1](https://www.cnblogs.com/KAWAKO/p/17077763.html),  [CH Instr 2](https://blog.csdn.net/xfysq_/article/details/138340373), [EN Instr 1](https://superuser.com/questions/1601631/create-ssh-tunnel-using-mobaxterm-on-windows),  [EN Instr 2](https://en-vegadocs.vega.izum.si/mobaxterm/)

Way 2 solves my problem, thanks!
