### ISSUE TITLE
'PhiAttention' object has no attribute 'q_layernorm'

### ISSUE THREAD

**Issue by SomnusKKK** [TangYuan96/MiniGPT-3D#6]
Hello，thank you for your excellent work，I find problem when I run demo，could you help me to solve the problem
`发生异常: AttributeError
'PhiAttention' object has no attribute 'q_layernorm'
  File "/data/wuzekai/code/MiniGPT-3D/minigpt4/models/base_model.py", line 211, in init_llm
    layer.self_attn.q_layernorm.weight.requires_grad = True
  File "/data/wuzekai/code/MiniGPT-3D/minigpt4/models/minigpt_base.py", line 37, in __init__
    self.llama_model, self.llama_tokenizer = self.init_llm(
  File "/data/wuzekai/code/MiniGPT-3D/minigpt4/models/minigpt_v2.py", line 55, in __init__
    super().__init__(
  File "/data/wuzekai/code/MiniGPT-3D/minigpt4/models/minigpt_v2.py", line 514, in from_config
    model = cls(
  File "/data/wuzekai/code/MiniGPT-3D/UI_demo.py", line 59, in <module>
    model = model_cls.from_config(model_config).to('cuda:{}'.format(args.gpu_id))
AttributeError: 'PhiAttention' object has no attribute 'q_layernorm'`

**Comment by SomnusKKK** [comment]
This is the PhiAttention, when I debug
 ```bash
      PhiAttention(
  (query_key_value): Linear(
    in_features=2560, out_features=7680, bias=True
    (lora_dropout): ModuleDict(
      (default): Dropout(p=0.05, inplace=False)
    )
    (lora_A): ModuleDict(
      (default): Linear(in_features=2560, out_features=64, bias=False)
    )
    (lora_B): ModuleDict(
      (default): Linear(in_features=64, out_features=7680, bias=False)
    )
    (lora_embedding_A): ParameterDict()
    (lora_embedding_B): ParameterDict()
  )
  (dense): Linear(
    in_features=2560, out_features=2560, bias=True
    (lora_dropout): ModuleDict(
      (default): Dropout(p=0.05, inplace=False)
    )
    (lora_A): ModuleDict(
      (default): Linear(in_features=2560, out_features=64, bias=False)
    )
    (lora_B): ModuleDict(
      (default): Linear(in_features=64, out_features=2560, bias=False)
    )
    (lora_embedding_A): ParameterDict()
    (lora_embedding_B): ParameterDict()
  )
  (attention_dropout): Dropout(p=0.0, inplace=False)
  (rotary_emb): PhiRotaryEmbedding()
)
```

**Comment by TangYuan96** [comment]
Hello!  Thanks for your interest in our work. 

I guess your problem is from  the [command](https://github.com/TangYuan96/MiniGPT-3D/blob/609082ef1f095a6d3bf62cfe1cddcf3807486b07/env_install.sh#L2)

If you use MiniGPT-3D in conda, you can directly run  the [command](https://github.com/TangYuan96/MiniGPT-3D/blob/609082ef1f095a6d3bf62cfe1cddcf3807486b07/env_install.sh#L2)


If not, you need to manually move **MiniGPT-3D/modeling_phi.py** to **model/phi /modeling_phi.py** in the transformers library.

If you still meet the problem in  conda,  you can try to follow the  [instruct](https://github.com/TangYuan96/MiniGPT-3D/blob/609082ef1f095a6d3bf62cfe1cddcf3807486b07/README.md?plain=1#L86) again.

**Comment by SomnusKKK** [comment]
I appreciate your quick response，I solve it.
